### ISSUE TITLE
0-stor: check list of consumers is properly populated

### ISSUE THREAD

**Issue by despiegk** [zero-os/0-stor#23] opened 2017-07-07 01:43 UTC
- spec was not ok, it was mentioned reference counter, needs to be full list
- the counter is required to quickly decide if the data is permanent or not and how many people have referenced this data

**Comment by zaibon** [comment] 2017-07-07 09:53
Code need to be updated indeed. I don't think we keep full list now.

**Comment by zaibon** [comment] 2017-07-10 11:33
duplicate of https://github.com/zero-os/0-stor/issues/25

**Closed by zaibon** 2017-07-10 11:33 UTC
Labels: process_duplicate, type_bug
