### ISSUE TITLE
Server Benchmarking program

### ISSUE THREAD

**Issue by chrisvdg** [zero-os/0-stor#382] opened 2017-12-04 11:47 UTC
As part of #296 we need to benchmark the zstor server without the client processing/overhead.

This program will:
* connect to a zstor server directly through grpc
* being able to test different configurations:
    * GOPROCMAX
    * authentication enable/disabled
    * different sizes of keys/values
    * concurrent client connections
    * different badger configurations
        * async write enable/disabled for badger

This program needs to work with the current server (with the new implementation) as well as the Alpha-8 server to have a comparison.

**Comment by GlenDC** [comment] 2017-12-04 16:14
> This program needs to work with the current server (with the new implementation) as well as the Alpha-8 server to have a comparison.

As alpha-8 is already released, and the branch is locked, I would simply recommend to make a alpha-8-benchmarks branch, where you can add this to.

**Comment by zaibon** [comment] 2017-12-13 13:52
duplicate of #380

**Closed by zaibon** 2017-12-13 13:52 UTC
Labels: mentor, process_duplicate, state_inprogress, type_feature
