### ISSUE TITLE
Implement client.datastor.Client interface on top on 0-db

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-stor#516] opened 2018-02-21 11:01 UTC
part of #515 

In order to be able to switch from zstordb to 0-db, we need to implement the [datastor.Client](https://godoc.org/github.com/zero-os/0-stor/client/datastor#Client) interface for 0-db

**Comment by iwanbk** [comment] 2018-02-26 10:58
How is the authentication mechanism?
I don't see jwt/IYO support in 0-db and see https://github.com/zero-os/0-db/issues/4 instead

**Comment by iwanbk** [comment] 2018-02-26 11:21
> How is the authentication mechanism?
> I don't see jwt/IYO support in 0-db and see zero-os/0-db#4 instead

Found the answer at https://github.com/zero-os/0-stor/issues/517#issue-299236129
"Once a namespace has been created on each shard, 0-stor client will receive a secret to authenticate against the 0-dbs and allow to access a namespace."

**Comment by zaibon** [comment] 2018-02-26 12:01
no indeed, JWT and IYO are out of the picture. 
So authentication is based on reservation and namespace.
An end user create a reservation for X amount of storages, a namespace with a quota of X is created on the 0-db but the 0-robot. The creation of the namespace will return a secret that needs to be used during the authentication to the 0-db.

So 0-stor client has a configuration for all the shards, a namespace and a secret for this namepsace.
At creation the 0-stor client send an AUTH command on all the shards to authentication the connection and select the namespace. From there the connection is secure and can be used freely

**Comment by iwanbk** [comment] 2018-02-27 04:49
One thing that confused me is this method
```go
   // Creates an object, using the given data.
    // The key of the object is generated by the server, and returned.
    CreateObject(data []byte) (key []byte, err error)
```

Based on the code i've read so far and manual test.
The object key is generated by server, with this format: `d:organization_0stor_namespace:sequence`.
`sequence` key will be incremented on each object write.(i.e. : if we upload `a.txt` twice, it will use two different keys)

See:
https://github.com/zero-os/0-stor/blob/1fed4cb32f51c31c5b9f99581eebdb0b8fe44ff9/server/db/memory/memory.go#L65-L69

and https://github.com/zero-os/0-stor/blob/1fed4cb32f51c31c5b9f99581eebdb0b8fe44ff9/server/db/badger/badger.go#L108-L114

To move forward, we have two options:
- add the key generation to 0-db
- put the key generation to client. I think this is the natural choice, most DBs i know let the user choose the key. But it seems we had a good reason to not do it?

**Comment by zaibon** [comment] 2018-02-27 06:18
0-db already return you the a key when you set an object, this is all foreseen.
To be used with 0-stor client, 0-db need to be used in [Direct key](https://github.com/zero-os/0-db#direct-key). In this mode 0-db give you back a key when you set an object.

**Comment by GlenDC** [comment] 2018-02-27 09:58
> "Once a namespace has been created on each shard, 0-stor client will receive a secret to authenticate against the 0-dbs and allow to access a namespace."

How is this secret securely stored? Or is that something a user will always have to do manual and thus it is up to the user to keep it save?

**Comment by iwanbk** [comment] 2018-02-27 10:04
> To be used with 0-stor client, 0-db need to be used in Direct key.

OK, it works, except the delete object part.
Got this error : `Unsupported on this mode`

**Comment by iwanbk** [comment] 2018-02-27 10:27
A WIP can be found on https://github.com/zero-os/0-stor/tree/zerodb/client/datastor/zerodb.

The test still deactivated, still looking for a best way to include or mock the 0-db server.

**Comment by iwanbk** [comment] 2018-02-28 04:23
> The test still deactivated, still looking for a best way to include or mock the 0-db server.

It has the test now, use https://github.com/tidwall/redcon to creates simple in memory 0-db server

**Comment by iwanbk** [comment] 2018-02-28 04:44
Now moving to implements [datastor.Shard](https://godoc.org/github.com/zero-os/0-stor/client/datastor#Shard) and [datastor.Cluster](https://godoc.org/github.com/zero-os/0-stor/client/datastor#Cluster)

**Comment by zaibon** [comment] 2018-02-28 07:38
> How is this secret securely stored? Or is that something a user will always have to do manual and thus it is up to the user to keep it save?

Yes it is something that after namespace creation is securely transmitted to the user, and it is then up to the user to keep it safe and provide it when needed.

**Comment by iwanbk** [comment] 2018-02-28 15:20
Except for `datastor.Client.ListObjectKeyIterator`, It seems all needed works for this issue has been finished.

I did a quick dirty change (79a566ccd212cfb512cbd08d8c56ae681311cade, change `zstor` cli to use 0-db) to do simple check, and it seems to be really work, thanks for the modular design.

I'm moving to root issue (#515),  will be back to this issue after maxime finished https://github.com/zero-os/0-db/issues/6

**Comment by GlenDC** [comment] 2018-03-01 14:46
> It has the test now, use https://github.com/tidwall/redcon to creates simple in memory 0-db server

I must be missing something here, as I don't see what your goal is here. You're saying to create an in-memory 0-db server (for testing purposes), but as far as I see, you are not using the 0-db code at all. You are simply providing a hash map over a redis interface, and that for testing purposes. If you really just want to isolate out the actual 0-db server, I think you can do much simpler, by having some (Internal) 0-db client hidden behind an interface, so you can simply provide that hashmap directly as an interface, rather than going with your current approach. This way you also avoid any issues in your tests that might be caused by the buggy redis-server you're using. And your tests will be much faster as well. In short, you will still not test the 0-db server itself, but will have much stabler tests.

**Comment by iwanbk** [comment] 2018-03-01 15:20
> edit: to be fair, no matter what the approach here is, you really don't have that useful unit tests here anyhow, the best would be if you could spawn an actual 0-db server from code. Embedded if possible.

agree with this

**Comment by GlenDC** [comment] 2018-03-21 00:09
What is still left to be done for this issue?

**Closed** 2018-03-22 07:52 UTC
Labels: state_inprogress, type_feature
